### ISSUE TITLE
Overflow does not happen for all processors

### ISSUE THREAD

**Issue by xhroot** [jackpal/bencode-go#18]
This test case does not overflow on ARM64 Graviton:

https://github.com/jackpal/bencode-go/blob/master/bencode_test.go#L253

The positive number is correctly decoded to a positive integer.

Propose we remove this test case that ensures some processors continue to exhibit problems with large number decoding.

**Comment by jackpal** [comment]
Well, it's also possible the ARM64 Graviton is incorrectly parsing/decoding the floating point number. Would have to research the Go spec to see what the Go language guarantees are.

**Comment by jackpal** [comment]
I removed the test. I considered trying to emulate the x86/x64 behavior on ARM, but I figured it would be difficult to emulate correctly.

I am a little worried that this architecture-specific behavior could be used to construct a torrent metadata header that acted differently when decoded on ARM vs x86/x64.
