### ISSUE TITLE
don't encode []byte as array of numbers

### ISSUE THREAD

**Issue by keks** [jackpal/bencode-go#2]
instead, encode them as, well, bytes.

Example: 
```
    bencode.Marshal(os.Stdout, []byte{'1', '2', '3'})
```
results in
```
    li49ei50ei51ee
```
instead of just
```
    3:123
```

Why not just use `string`? ~~Because in Go, they, by definition, should only contain valid Unicode. bencode "strings" however allow binary data.~~

Edit: okay I just realized this is wrong. Anyway, `[]byte` should be handled the same way!

**Comment by martinlindhe** [comment]
Not a bug.

In your example, you should are  encoding the runes for "1", "2", "3", and not their byte values.

 `bencode.Marshal(os.Stdout, []byte{1, 2, 3})` is what you'd want

**Comment by keks** [comment]
> In your example, you should are encoding the runes for "1", "2", "3", and not their byte values.

Well, the runes are converted to bytes during `[]byte{'1', '2', '3'}`. Afterwards, it's a `[]byte`, and you can simply encode it as I proposed, yielding a more readable and shorter bencode representation.

You can find an obvious example that illustrates my point [here](http://play.golang.org/p/svsb34cwqJ)

**Comment by martinlindhe** [comment]
Yes, '1' is a rune value and it fits in a byte value.

'本' is also a rune value (from your example), but does not fit in a byte value.

Your proposal doesn't make sense because it would turn an literal representation of '1' (byte value 49) into byte value 1.

**Comment by keks** [comment]
> Your proposal doesn't make sense because it would turn an literal representation of '1' (byte value 49) into byte value 1.

`[]byte{'1', '2', '3'}` is part of the Go language and this is where the conversion happens, are you saying it doesn't make sense? That means you're saying the Go spec doesn't make sense.

If you want, we can change the proposal to

    bencode.Marshal(os.Stdout, []byte{0x31, 0x32, 0x33})

Which is _exactly_ the same library code wise. I want the code above to produce

    s:123

instead of 

    li49ei50ei51ee

which, as I stated above, yields a more readable and shorter bencode representation.

**Comment by martinlindhe** [comment]
No, i am saying that your proposal of turning ascii '1' into byte 1 dont make sense, and is no part of the go spec. You are casting a rune '1' into a byte by using `[]byte{...}`

**Comment by martinlindhe** [comment]
also, if you want bencode a string, pass it a string, not a byte array.

`bencode.Marshal(os.Stdout, "123")` 
// Output: 3:123

I do not know what "s:123" would mean in bencode, the leading digit is the length of the following character sequence.

**Comment by keks** [comment]
Okay I think I found the point of confusion. You seem to think that 

    s:123

means `[]byte{1,2,3}`. It doesn't. It means `[]byte{0x31,0x32,0x33}`. I thought it was more obvious what I meant if I just cast the runes to bytes (which in this case was okay since all of the runes have values less than 256).

I want this bencode library  to use the bencode string representation for values of type `[]byte` instead of lists of integers, since it is (a) equivalent (b) more readable (depending on the bytes obviously) and (c) is shorter.

A string in bencode is equivalent to a list of bytes. Also it is shorter. Why treat them differently?

>I do not know what "s:123" would mean in bencode, the leading digit is the length of the following character sequence.

Whoops. meant to write `3:123`. Sorry. It's fixed now.

**Comment by martinlindhe** [comment]
Okay, thanks for your patience. I think i'm starting to understand the issue.

So, "3:123" is a encoded byte string (bencode term), bencode-go only creates this formatting if fed by a string.

if bencode-go is fed by a []byte or []int ,etc, it encodes this as a series of integers.

You expect a []byte to be encoded as a byte string.

**Comment by keks** [comment]
Exactly. Since bencode does not know the type `byte` we have to take what's there, and that's bencode integers. For arrays of them, bencode strings seem more appropriate.

**Comment by martinlindhe** [comment]
@keks could you possibly have a look at the patch?

**Comment by keks** [comment]
Looks great. Do the tests pass?

**Comment by martinlindhe** [comment]
Yes and no.

No previous tests existed on encoding of []byte, so no tests failed.
I added a small test for []byte encoding (this PR), and []int, https://github.com/martinlindhe/bencode-go/commit/7e1d4eebeb52910b49be87a8c6d1a5712109fe49#diff-e7963680a84954e8d5158150d7fb1a2bR363

**Comment by keks** [comment]
I saw the tests and if those pass, great.
