### ISSUE TITLE
Handle panic

### ISSUE THREAD

**Issue by casey** [jackpal/bencode-go#5]
I received the panic at struct.go#L56. It would be great if the panic would be translated into an error return value instead.

**Comment by martinlindhe** [comment]
I would say this is not-a-bug.

The panic at https://github.com/jackpal/bencode-go/blob/master/struct.go#L55
occurs only when you call the function with non-supported data types.
There is no point in such a case, to return an error message to the user.

Additionally, the panic does contain the error message.
